name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 2.19.6
        channel: stable

    - name: Install dependencies
      run: flutter pub get

    - name: Build Linux
      run: flutter build linux
