name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: beta

    - name: Install dependencies
      run: flutter pub get

    - name: Set up build environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential ninja-build

    - name: Build Linux
      run: |
        export CMAKE_MAKE_PROGRAM=/usr/bin/ninja
        export CMAKE_CXX_COMPILER=/usr/bin/g++
        flutter build linux
